# Generated by Django 3.0.5 on 2020-04-29 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amino',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=150)),
                ('Flavors', models.IntegerField()),
                ('Rating', models.FloatField()),
                ('Price', models.FloatField()),
                ('Per', models.FloatField()),
                ('Category', models.CharField(max_length=100)),
                ('Disc', models.CharField(max_length=1000)),
                ('TopFlavor', models.CharField(max_length=100)),
                ('Url', models.CharField(max_length=500)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Bcaa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=150)),
                ('Flavors', models.IntegerField()),
                ('Rating', models.FloatField()),
                ('Price', models.FloatField()),
                ('Per', models.FloatField()),
                ('Category', models.CharField(max_length=100)),
                ('Disc', models.CharField(max_length=1000)),
                ('TopFlavor', models.CharField(max_length=100)),
                ('Url', models.CharField(max_length=500)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Beta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=150)),
                ('Flavors', models.IntegerField()),
                ('Rating', models.FloatField()),
                ('Price', models.FloatField()),
                ('Per', models.FloatField()),
                ('Category', models.CharField(max_length=100)),
                ('Disc', models.CharField(max_length=1000)),
                ('TopFlavor', models.CharField(max_length=100)),
                ('Url', models.CharField(max_length=500)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Caffeine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=150)),
                ('Flavors', models.IntegerField()),
                ('Rating', models.FloatField()),
                ('Price', models.FloatField()),
                ('Per', models.FloatField()),
                ('Category', models.CharField(max_length=100)),
                ('Disc', models.CharField(max_length=1000)),
                ('TopFlavor', models.CharField(max_length=100)),
                ('Url', models.CharField(max_length=500)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=150)),
                ('Flavors', models.IntegerField()),
                ('Rating', models.FloatField()),
                ('Price', models.FloatField()),
                ('Per', models.FloatField()),
                ('Category', models.CharField(max_length=100)),
                ('Disc', models.CharField(max_length=1000)),
                ('TopFlavor', models.CharField(max_length=100)),
                ('Url', models.CharField(max_length=500)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NewOne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=150)),
                ('Flavors', models.IntegerField()),
                ('Rating', models.FloatField()),
                ('Price', models.FloatField()),
                ('Per', models.FloatField()),
                ('Category', models.CharField(max_length=100)),
                ('Disc', models.CharField(max_length=1000)),
                ('TopFlavor', models.CharField(max_length=100)),
                ('Url', models.CharField(max_length=500)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=150)),
                ('Flavors', models.IntegerField()),
                ('Rating', models.FloatField()),
                ('Price', models.FloatField()),
                ('Per', models.FloatField()),
                ('Category', models.CharField(max_length=100)),
                ('Disc', models.CharField(max_length=1000)),
                ('TopFlavor', models.CharField(max_length=100)),
                ('Url', models.CharField(max_length=500)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=150)),
                ('Flavors', models.IntegerField()),
                ('Rating', models.FloatField()),
                ('Price', models.FloatField()),
                ('Per', models.FloatField()),
                ('Category', models.CharField(max_length=100)),
                ('Disc', models.CharField(max_length=1000)),
                ('TopFlavor', models.CharField(max_length=100)),
                ('Url', models.CharField(max_length=500)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Protein',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=150)),
                ('Flavors', models.IntegerField()),
                ('Rating', models.FloatField()),
                ('Price', models.FloatField()),
                ('Per', models.FloatField()),
                ('Category', models.CharField(max_length=100)),
                ('Disc', models.CharField(max_length=1000)),
                ('TopFlavor', models.CharField(max_length=100)),
                ('Url', models.CharField(max_length=500)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Recovery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=150)),
                ('Flavors', models.IntegerField()),
                ('Rating', models.FloatField()),
                ('Price', models.FloatField()),
                ('Per', models.FloatField()),
                ('Category', models.CharField(max_length=100)),
                ('Disc', models.CharField(max_length=1000)),
                ('TopFlavor', models.CharField(max_length=100)),
                ('Url', models.CharField(max_length=500)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=150)),
                ('Flavors', models.IntegerField()),
                ('Rating', models.FloatField()),
                ('Price', models.FloatField()),
                ('Per', models.FloatField()),
                ('Category', models.CharField(max_length=100)),
                ('Disc', models.CharField(max_length=1000)),
                ('TopFlavor', models.CharField(max_length=100)),
                ('Url', models.CharField(max_length=500)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
