# Generated by Django 3.0.5 on 2020-04-29 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20200428_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amino',
            name='Price',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='amino',
            name='Rating',
            field=models.CharField(default='Not Rated', max_length=25),
        ),
        migrations.AlterField(
            model_name='bcaa',
            name='Price',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='bcaa',
            name='Rating',
            field=models.CharField(default='Not Rated', max_length=25),
        ),
        migrations.AlterField(
            model_name='beta',
            name='Price',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='beta',
            name='Rating',
            field=models.CharField(default='Not Rated', max_length=25),
        ),
        migrations.AlterField(
            model_name='caffeine',
            name='Price',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='caffeine',
            name='Rating',
            field=models.CharField(default='Not Rated', max_length=25),
        ),
        migrations.AlterField(
            model_name='lc',
            name='Price',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='lc',
            name='Rating',
            field=models.CharField(default='Not Rated', max_length=25),
        ),
        migrations.AlterField(
            model_name='newone',
            name='Price',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='newone',
            name='Rating',
            field=models.CharField(default='Not Rated', max_length=25),
        ),
        migrations.AlterField(
            model_name='post',
            name='Price',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='Rating',
            field=models.CharField(default='Not Rated', max_length=25),
        ),
        migrations.AlterField(
            model_name='pre',
            name='Price',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='pre',
            name='Rating',
            field=models.CharField(default='Not Rated', max_length=25),
        ),
        migrations.AlterField(
            model_name='protein',
            name='Price',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='protein',
            name='Rating',
            field=models.CharField(default='Not Rated', max_length=25),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='Price',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='Rating',
            field=models.CharField(default='Not Rated', max_length=25),
        ),
        migrations.AlterField(
            model_name='test',
            name='Price',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='Rating',
            field=models.CharField(default='Not Rated', max_length=25),
        ),
    ]
