# Generated by Django 3.0.5 on 2020-04-29 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20200428_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amino',
            name='Per',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='bcaa',
            name='Per',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='beta',
            name='Per',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='caffeine',
            name='Per',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='lc',
            name='Per',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='newone',
            name='Per',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='post',
            name='Per',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='pre',
            name='Per',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='protein',
            name='Per',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='Per',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='test',
            name='Per',
            field=models.CharField(max_length=25),
        ),
    ]
