# Generated by Django 3.0.5 on 2020-05-09 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_auto_20200508_2212'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
